name: Object Detection Inference Visualized
description: A blog-style application to visualize object detection workflow
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 2.0
date: "2022-04-04"

runtimes:
  - editor: Workbench
    kernel: Python 3.9
    edition: Standard

tasks:
  - type: run_session
    name: Install Dependencies
    script: cml/install_dependencies.py
    memory: 5
    cpu: 2

  - type: start_application
    name: Launch Streamlit Application
    subdomain: streamlit
    script: cml/launch_app.py
    short_summary: Starting Streamlit application
    cpu: 2
    memory: 4
    environment_variables:
      TASK_TYPE: START_APPLICATION
